### ISSUE TITLE
 您好，请问能问一下你用的板子是什么型号的嘛，我最近也在做一个类似的项目，现在没有什么头绪

### ISSUE THREAD

**Issue by zengfanyi** [Lustrew/Face-Recognition-of-DeepID_Forward_Use_C#1]
您这个是把网络用翻译成c语言的形式了嘛

**Comment by Lucas-Wye** [comment]
我用的是全志v5的开发板，因为上面没有深度学习平台(tf,pytorch等)可以用，所以自己造了个轮子……
就是把前向传播用C重写了一下。

**Comment by zengfanyi** [comment]
好的，我现在要做的内容其实也是差不多的。不过可能就是网络结构会比您的这个复杂点，目前打算在arm的a9上实现。最近在做一些调研
