### ISSUE TITLE
准确率

### ISSUE THREAD

**Issue by balalay** [Lustrew/Face-Recognition-of-DeepID_Forward_Use_C#2]
您好，您的项目非常清晰明了，使我收获良多，但是运行的时候准确率似乎没有90%这么高。请问，您得到的90%的准确率用的是什么数据呢？

**Comment by Lucas-Wye** [comment]
训练用的是CASIA的数据集，然后90%是在LFW数据集上测试得到的

**Comment by balalay** [comment]
请问您这个卷积的各层参数是自己在CASIA数据集上训练得到的吗？90%的准确率是用余弦相似度测得的吗？

**Comment by Lucas-Wye** [comment]
yes
